### PR TITLE
Milestone 1: Setup environment

### PR DESCRIPTION
**Pull request by elmar8287**
- Update Node.js and npm up to the newest version
- Setup React app according [documentation](https://reactjs.org/docs/create-a-new-react-app.html#create-react-app)

### CODE REVIEW

**Review by vichuge — CHANGES_REQUESTED** [review]
# Required Changes ♻️ ⚠️ 🚦 

Hi dear student, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

mario_ladders

## Good points 👍 
You used proper GitHub Flow ✔️
Your linter checks are all passing ✔️
Your PR messages are descriptive ✔️

## Aspects to improve ♻️

- [x] The project looks good, you have the required elements, the only problem is that you have it inside another folder called `math` in place on the root project. Please, is important that all this could be on the root. Not inside another project as you made it, this is important because when you deploy the page, to have all in another project make your URL address bigger and that's not good for SEO purposes, not if is not required. Please, do this change and you'll be ready for next project. 🐶 
image


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by elmar8287** [comment]
Dear @vichuge 🥇 

Hope you are well. Thank you for your review. I have fixed you mentioned note. The root corrected.

My regards 💯

**Review by henatan99 — APPROVED** [review]
Hi @elmar8287 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by elmar8287** [comment]
Hi @henatan99 🥇 

Thanks for your review. 

Best regards,

Elmar

**Pull request merged**
